import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import { useState, useEffect } from 'react'
import Link from 'next/link'

import db from '../../db'

// Date.prototype.ymd = function() {
//     var mm = this.getMonth() + 1; // getMonth() is zero-based
//     var dd = this.getDate();
//     console.log(new Date().toISOString().slice(0, 10))
//     return [this.getFullYear(),
//             (mm>9 ? '' : '0') + mm,
//             (dd>9 ? '' : '0') + dd
//            ].join('-');
//   };

 

export default function Home() {
    const [sudokus, setSudokus] = useState([])
    // const date = new Date()
    const startDate = new Date(Date.UTC(2021, 0, 1))
    const endDate = new Date()
    // const januaryFirst2021 = new Date(Date.UTC(2021, 1, 1))
    // const januaryTen2021 = new Date(Date.UTC(2021, 1, 10))
    let day =  startDate
    const dateList = []
    const converter = {'Jan' : '01', 'Feb': '02', 'Mar': '03', 'Apr': '04', 'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08', 'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'}
    while(day <= endDate) {
        const date = day.toUTCString().slice(5,7)
        const month = converter[day.toUTCString().slice(8,11)]
        const year = day.toUTCString().slice(12, 16)
        console.log(year + '-' + month+'-'+date)
        console.log()
    
        dateList.push(year + '-' + month+'-'+date)
        // Increment day
        day.setUTCDate(day.getUTCDate() + 1)
    }

    console.log(dateList)
    // console.log(date.ymd())
    // const params = {
    //     TableName: "Sudoku",
    // };
    
    // fetchSudokus()
    // async function fetchSudokus() {
    //     const scanResults = [];
    //     let items;
    //     do{
    //         items =  await db.scan(params).promise();
    //         console.log(items, ' itemssss')
    //         items.Items.forEach((item) => scanResults.push(item));
    //         params.ExclusiveStartKey  = items.LastEvaluatedKey;
    //     }while(typeof items.LastEvaluatedKey !== "undefined");
    //     console.log(scanResults, 'scanresults')
    //     const paths =  scanResults.map(sudoku => { return sudoku.date })
    //     setSudokus(scanResults)
    //     console.log('paths: ', scanResults)  
    // }
    //   const sudokuData = await DataStore.query(Sudoku)
    //   console.log('sudokuData: ', sudokuData)
    //   setSudokus(sudokuData)
    // const subscription = DataStore.observe(Sudoku).subscribe(() => fetchSudokus())
    // return () => subscription.unsubscribe()
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Sudoku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* {sudokus.map(sudoku => (
          <Link href={`/testing/${sudoku.date}`}>
            <a>
              {sudoku.id}
            </a>
          </Link>
        ))} */}
        <Link href={`/testing/2021-01-01`}>
            <a>2021-01-01</a>
        </Link>
        <Link href={`/testing/2021-01-02`}>
            <a>2021-01-02</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
