
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import db from '../db'
import { dateToString } from '../utils/dates'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import Calendar from '../components/Calendar'
 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sudoku</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />   
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calendar sudokuDate={new Date(Date.UTC(2021, 0, 1))} realLifeDate={new Date()}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const params = {
    TableName: 'Sudoku',
    Key: {
      date: dateToString(new Date(Date.UTC(2021, 0, 1)))
    }
  };

  let sudoku
  try {
     sudoku = await db.get(params).promise()
  } catch(err) {
    console.log(err)
  }
 
  return {
    props: sudoku.Item
    // props: {}, // will be passed to the page component as props
  }
}